version: '3.8'
services:
  auth-service:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/authdb
      - JWT_SECRET=supersecretkey
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"