version: '3.8'
services:
  user-service:
    build: .
    ports:
      - "5002:5002"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/userdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27018:27017"